// <auto-generated>
// GENERATED from packages/core/src/win-channel.ts by scripts/generate-win-channel.mjs.
// Do not edit — the schema in core is the single source of truth (win-host-spec §2).
// </auto-generated>
#nullable enable
using System.Text.Json;
using System.Text.Json.Serialization;

namespace PrismHost.Channel;

public readonly record struct ChannelRect(
    [property: JsonPropertyName("x")] double X,
    [property: JsonPropertyName("y")] double Y,
    [property: JsonPropertyName("w")] double W,
    [property: JsonPropertyName("h")] double H);

public static class Ops
{
    public const string SurfaceCreate = "surface.create";
    public const string SurfaceDestroy = "surface.destroy";
    public const string SurfaceSetRect = "surface.setRect";
    public const string SurfaceSetOpacity = "surface.setOpacity";
    public const string SurfaceSetZ = "surface.setZ";
    public const string SurfaceSetVisible = "surface.setVisible";
    public const string SurfaceGoBack = "surface.goBack";
    public const string SurfaceNavigate = "surface.navigate";
    public const string SurfaceInject = "surface.inject";
    public const string SurfaceFreeze = "surface.freeze";
    public const string SurfaceReveal = "surface.reveal";
    public const string SurfaceSuspend = "surface.suspend";
    public const string SurfaceResume = "surface.resume";
    public const string SurfaceSetPeek = "surface.setPeek";
    public const string SurfaceShowIntermission = "surface.showIntermission";
    public const string SurfaceHideIntermission = "surface.hideIntermission";
    public const string SurfaceSetIntermissionSkip = "surface.setIntermissionSkip";
    public const string SurfaceSetAdInfo = "surface.setAdInfo";
    public const string SurfaceSetMuted = "surface.setMuted";
    public const string SurfaceSetViewport = "surface.setViewport";
    public const string SurfaceSetNowPlaying = "surface.setNowPlaying";
    public const string SurfaceSetChrome = "surface.setChrome";
    public const string SurfaceSetFocused = "surface.setFocused";
    public const string SurfaceSetPageInput = "surface.setPageInput";
    public const string SurfaceSendKey = "surface.sendKey";
    public const string SurfaceHover = "surface.hover";
    public const string SurfaceScrub = "surface.scrub";
    public const string SurfaceTypeText = "surface.typeText";
    public const string SurfaceEvaluate = "surface.evaluate";
    public const string SurfaceVeilImagery = "surface.veilImagery";
    public const string SurfaceCaptureAudio = "surface.captureAudio";
    public const string SurfaceCreateVisualization = "surface.createVisualization";
    public const string SurfaceSetVisualizationFeed = "surface.setVisualizationFeed";
    public const string SurfaceSetPresence = "surface.setPresence";
    public const string UiRoute = "ui.route";
    public const string UiTapResult = "ui.tapResult";
    public const string DisplaySetBrightness = "display.setBrightness";
    public const string DisplaySetPower = "display.setPower";
    public const string MediaLaunch = "media.launch";
    public const string MediaSetSpeakers = "media.setSpeakers";
    public const string MediaListApps = "media.listApps";
    public const string MediaAppSkip = "media.appSkip";
    public const string MediaAppType = "media.appType";
    public const string MediaAppBack = "media.appBack";
    public const string MediaServeAudio = "media.serveAudio";
    public const string MediaWebrtcOffer = "media.webrtcOffer";
    public const string MediaWebrtcIce = "media.webrtcIce";
    public const string MediaWebrtcClose = "media.webrtcClose";
    public const string InputStartPairing = "input.startPairing";
    public const string InputListRemotes = "input.listRemotes";
    public const string UpdateFetchManifest = "update.fetchManifest";
    public const string UpdateApply = "update.apply";
    public const string StoreSet = "store.set";
    public const string AlarmSetTone = "alarm.setTone";
    public const string NetSubmitCompatReport = "net.submitCompatReport";
    public const string NetApplyBlockHosts = "net.applyBlockHosts";
    public const string NetFetchStatic = "net.fetchStatic";
    public const string NetFetchKeyed = "net.fetchKeyed";
    public const string RuntimeError = "runtime.error";
    public const string RemotePaired = "remote.paired";
    public const string RemotePairing = "remote.pairing";
    public const string RemotePairedCount = "remote.paired-count";
    public const string HttpResponse = "http.response";
}

public static class HostCalls
{
    public const string Init = "init";
    public const string Resize = "resize";
    public const string Event = "event";
    public const string Input = "input";
    public const string PromoteHero = "promoteHero";
    public const string SetHeroSize = "setHeroSize";
    public const string RefreshTile = "refreshTile";
    public const string Http = "http";
    public const string MintPairing = "mintPairing";
    public const string SwitchTo = "switchTo";
    public const string Resolve = "resolve";
    public const string AddCatalogTile = "addCatalogTile";
    public const string RemoveTile = "removeTile";
    public const string ToggleFullscreen = "toggleFullscreen";
    public const string PosterPlan = "posterPlan";
    public const string MarkPlan = "markPlan";
    public const string RedeemStreamTicket = "redeemStreamTicket";
    public const string State = "state";
    public const string SetTileMode = "setTileMode";
    public const string Rects = "rects";
    public const string UpdateTile = "updateTile";
    public const string SetLayout = "setLayout";
    public const string AddCustomTile = "addCustomTile";
    public const string ReplaceWithCatalogTile = "replaceWithCatalogTile";
    public const string ReplaceWithCustomTile = "replaceWithCustomTile";
    public const string SaveShortcut = "saveShortcut";
    public const string RemoveShortcut = "removeShortcut";
    public const string ApplyShortcut = "applyShortcut";
    public const string StartFraming = "startFraming";
    public const string FinishFraming = "finishFraming";
    public const string TileCommand = "tileCommand";
    public const string TapItem = "tapItem";
    public const string SaveMasterLayout = "saveMasterLayout";
    public const string RemoveMasterLayout = "removeMasterLayout";
    public const string ApplyMasterLayout = "applyMasterLayout";
    public const string PreviewLayout = "previewLayout";
    public const string SlotPurposes = "slotPurposes";
    public const string PopupDecision = "popupDecision";
    public const string SaveScene = "saveScene";
    public const string RemoveScene = "removeScene";
    public const string ApplyScene = "applyScene";
    public const string SimilarLayouts = "similarLayouts";
    public const string ModelState = "modelState";
    public const string ModelSaveApp = "modelSaveApp";
    public const string ModelSaveFacet = "modelSaveFacet";
    public const string ModelRemoveFacet = "modelRemoveFacet";
    public const string ModelSaveLayout = "modelSaveLayout";
    public const string ModelLayoutDuplicates = "modelLayoutDuplicates";
    public const string ModelArchiveLayout = "modelArchiveLayout";
    public const string ModelSaveScene = "modelSaveScene";
    public const string ModelRemoveScene = "modelRemoveScene";
    public const string ModelApplyScene = "modelApplyScene";
    public const string Players = "players";
    public const string SwitchPlayer = "switchPlayer";
    public const string VideoState = "videoState";
    public const string VideoLibrary = "videoLibrary";
    public const string VideoPlay = "videoPlay";
    public const string VideoServices = "videoServices";
    public const string VideoSwitch = "videoSwitch";
    public const string VideoPlayOn = "videoPlayOn";
    public const string VideoProfile = "videoProfile";
    public const string VideoLibraryTab = "videoLibraryTab";
    public const string VideoProfilesView = "videoProfilesView";
    public const string VideoProfileSet = "videoProfileSet";
    public const string VideoProfileExclude = "videoProfileExclude";
    public const string VideoRefreshStale = "videoRefreshStale";
    public const string VideoFreshness = "videoFreshness";
    public const string VideoSettings = "videoSettings";
    public const string VideoUpdatesStatus = "videoUpdatesStatus";
    public const string VideoRefreshApp = "videoRefreshApp";
    public const string VideoSetPause = "videoSetPause";
    public const string VideoProfilesCommit = "videoProfilesCommit";
    public const string VideoPresetSave = "videoPresetSave";
    public const string VideoPresetDelete = "videoPresetDelete";
    public const string VideoPresetApply = "videoPresetApply";
    public const string VideoCancelPick = "videoCancelPick";
    public const string VideoRemoveInfo = "videoRemoveInfo";
    public const string VideoRemoveContinue = "videoRemoveContinue";
    public const string VideoEpisodes = "videoEpisodes";
    public const string VideoListInfo = "videoListInfo";
    public const string VideoListSet = "videoListSet";
    public const string VideoArtOf = "videoArtOf";
    public const string VideoPlayEpisode = "videoPlayEpisode";
    public const string VideoMultiview = "videoMultiview";
    public const string TitleEpisodes = "titleEpisodes";
    public const string TitleAlsoOn = "titleAlsoOn";
    public const string TitleEpisodePlay = "titleEpisodePlay";
    public const string BootTimings = "bootTimings";
    public const string VideoResync = "videoResync";
    public const string VideoStartOver = "videoStartOver";
    public const string VideoNextEpisode = "videoNextEpisode";
    public const string VideoTrack = "videoTrack";
    public const string VideoMenu = "videoMenu";
    public const string VideoSearch = "videoSearch";
    public const string VideoLookup = "videoLookup";
    public const string VideoLookupState = "videoLookupState";
    public const string VideoBrowse = "videoBrowse";
    public const string VideoBrowsePlay = "videoBrowsePlay";
    public const string VideoBingeView = "videoBingeView";
    public const string VideoBingeSet = "videoBingeSet";
    public const string VideoBingeHide = "videoBingeHide";
    public const string VideoBingeHidden = "videoBingeHidden";
    public const string VideoBingePlay = "videoBingePlay";
    public const string VideoBrowseRow = "videoBrowseRow";
    public const string VideoLookupView = "videoLookupView";
    public const string VideoPlayResult = "videoPlayResult";
    public const string VideoTune = "videoTune";
    public const string VideoForgetProfile = "videoForgetProfile";
    public const string VideoProfileChoose = "videoProfileChoose";
    public const string VideoProfileAsk = "videoProfileAsk";
    public const string VideoForgetWatch = "videoForgetWatch";
    public const string VideoRefreshLists = "videoRefreshLists";
    public const string LensChoose = "lensChoose";
    public const string LensSetTmdbKey = "lensSetTmdbKey";
    public const string LensDisclosure = "lensDisclosure";
    public const string LensHasKey = "lensHasKey";
    public const string ModelTemplates = "modelTemplates";
    public const string ModelInstantiateTemplate = "modelInstantiateTemplate";
    public const string ModelMigrate = "modelMigrate";
    public const string NewsShelf = "newsShelf";
    public const string ListeningChips = "listeningChips";
    public const string MusicState = "musicState";
    public const string RevealMusic = "revealMusic";
    public const string CollapseMusic = "collapseMusic";
    public const string RestyleVisualization = "restyleVisualization";
    public const string MusicRecent = "musicRecent";
    public const string PlayRecent = "playRecent";
    public const string MusicLibrary = "musicLibrary";
    public const string PlayCollection = "playCollection";
    public const string ResumeService = "resumeService";
    public const string MusicLookup = "musicLookup";
    public const string MusicLookupState = "musicLookupState";
    public const string MusicLookupPick = "musicLookupPick";
    public const string MusicAddToPlaylist = "musicAddToPlaylist";
    public const string MusicStationFromSong = "musicStationFromSong";
    public const string RecycleApp = "recycleApp";
    public const string MusicSources = "musicSources";
    public const string SetIntermissionAmbient = "setIntermissionAmbient";
    public const string RegisterStylePalettes = "registerStylePalettes";
    public const string NoteArtworkColors = "noteArtworkColors";
    public const string SceneStep = "sceneStep";
    public const string UiRoute = "uiRoute";
    public const string ModelClassifyLayout = "modelClassifyLayout";
    public const string ModelNearestBucket = "modelNearestBucket";
    public const string ModelRepresentativeRect = "modelRepresentativeRect";
    public const string ModelClassRatio = "modelClassRatio";
    public const string ModelFacetPresets = "modelFacetPresets";
    public const string ModelPresetFacet = "modelPresetFacet";
    public const string ModelLoginRedirect = "modelLoginRedirect";
    public const string ModelFacetPickerJs = "modelFacetPickerJs";
    public const string ModelFacetPickPollJs = "modelFacetPickPollJs";
    public const string ModelFacetPickStopJs = "modelFacetPickStopJs";
    public const string ModelPickPollJs = "modelPickPollJs";
    public const string ModelPickStopJs = "modelPickStopJs";
    public const string ModelSelectorRectJs = "modelSelectorRectJs";
    public const string ModelOpenAppSurface = "modelOpenAppSurface";
    public const string ModelCloseAppSurface = "modelCloseAppSurface";
}

public static class SurfaceEvents
{
    public const string LoadFinished = "load-finished";
    public const string FirstPaint = "first-paint";
    public const string AdapterReady = "adapter-ready";
    public const string Playback = "playback";
    public const string Interaction = "interaction";
    public const string Navigated = "navigated";
    public const string FocusResult = "focus-result";
    public const string AdBreak = "ad-break";
    public const string SkipAvailable = "skip-available";
    public const string AdInfo = "ad-info";
    public const string ListenerLost = "listener-lost";
    public const string AppAdBreak = "app-ad-break";
    public const string AppSkipAvailable = "app-skip-available";
    public const string AppForeground = "app-foreground";
    public const string IntermissionSkip = "intermission-skip";
    public const string MediaPosition = "media-position";
    public const string NowPlaying = "now-playing";
    public const string Session = "session";
    public const string FullscreenElement = "fullscreen-element";
    public const string Popup = "popup";
    public const string MusicResult = "music-result";
}

/// <summary>One command from core; RequestId is set on request-lane ops.</summary>
public sealed record CommandEnvelope(
    [property: JsonPropertyName("op")] string Op,
    [property: JsonPropertyName("requestId")] double? RequestId = null);

/// <summary>surface.create [M1]</summary>
public sealed record SurfaceCreateCommand(
    [property: JsonPropertyName("id")] string Id,
    [property: JsonPropertyName("profile")] string Profile,
    [property: JsonPropertyName("background")] string Background,
    [property: JsonPropertyName("zoom")] double Zoom,
    [property: JsonPropertyName("blocking")] bool Blocking,
    [property: JsonPropertyName("placeholder")] bool Placeholder,
    [property: JsonPropertyName("viewport")] string? Viewport = null,
    [property: JsonPropertyName("uaPlatform")] string? UaPlatform = null,
    [property: JsonPropertyName("launch")] string? Launch = null,
    [property: JsonPropertyName("label")] string? Label = null,
    [property: JsonPropertyName("kind")] string? Kind = null);

/// <summary>surface.destroy [M1]</summary>
public sealed record SurfaceDestroyCommand(
    [property: JsonPropertyName("id")] string Id);

/// <summary>surface.setRect [M1]</summary>
public sealed record SurfaceSetRectCommand(
    [property: JsonPropertyName("id")] string Id,
    [property: JsonPropertyName("rect")] ChannelRect Rect);

/// <summary>surface.setOpacity [M1]</summary>
public sealed record SurfaceSetOpacityCommand(
    [property: JsonPropertyName("id")] string Id,
    [property: JsonPropertyName("opacity")] double Opacity);

/// <summary>surface.setZ [M1]</summary>
public sealed record SurfaceSetZCommand(
    [property: JsonPropertyName("id")] string Id,
    [property: JsonPropertyName("z")] double Z);

/// <summary>surface.setVisible [stub until later milestone]</summary>
public sealed record SurfaceSetVisibleCommand(
    [property: JsonPropertyName("id")] string Id,
    [property: JsonPropertyName("visible")] bool Visible);

/// <summary>surface.goBack (request lane — answer via PrismRuntime.resolve) [stub until later milestone]</summary>
public sealed record SurfaceGoBackCommand(
    [property: JsonPropertyName("id")] string Id);

/// <summary>surface.navigate [M1]</summary>
public sealed record SurfaceNavigateCommand(
    [property: JsonPropertyName("id")] string Id,
    [property: JsonPropertyName("url")] string Url);

/// <summary>surface.inject [M1]</summary>
public sealed record SurfaceInjectCommand(
    [property: JsonPropertyName("id")] string Id,
    [property: JsonPropertyName("css")] string? Css = null,
    [property: JsonPropertyName("js")] string? Js = null);

/// <summary>surface.freeze [M1]</summary>
public sealed record SurfaceFreezeCommand(
    [property: JsonPropertyName("id")] string Id);

/// <summary>surface.reveal [M1]</summary>
public sealed record SurfaceRevealCommand(
    [property: JsonPropertyName("id")] string Id,
    [property: JsonPropertyName("durationMs")] double DurationMs);

/// <summary>surface.suspend [M1]</summary>
public sealed record SurfaceSuspendCommand(
    [property: JsonPropertyName("id")] string Id);

/// <summary>surface.resume [M1]</summary>
public sealed record SurfaceResumeCommand(
    [property: JsonPropertyName("id")] string Id);

/// <summary>surface.setPeek [M1]</summary>
public sealed record SurfaceSetPeekCommand(
    [property: JsonPropertyName("id")] string Id,
    [property: JsonPropertyName("peeking")] bool Peeking);

/// <summary>surface.showIntermission [M1]</summary>
public sealed record SurfaceShowIntermissionCommand(
    [property: JsonPropertyName("id")] string Id,
    [property: JsonPropertyName("source")] string Source);

/// <summary>surface.hideIntermission [M1]</summary>
public sealed record SurfaceHideIntermissionCommand(
    [property: JsonPropertyName("id")] string Id);

/// <summary>surface.setIntermissionSkip [M1]</summary>
public sealed record SurfaceSetIntermissionSkipCommand(
    [property: JsonPropertyName("id")] string Id,
    [property: JsonPropertyName("available")] bool Available,
    [property: JsonPropertyName("target")] string? Target = null);

/// <summary>surface.setAdInfo [M1]</summary>
public sealed record SurfaceSetAdInfoCommand(
    [property: JsonPropertyName("id")] string Id,
    [property: JsonPropertyName("count")] string Count,
    [property: JsonPropertyName("remaining")] double Remaining);

/// <summary>surface.setMuted [M1]</summary>
public sealed record SurfaceSetMutedCommand(
    [property: JsonPropertyName("id")] string Id,
    [property: JsonPropertyName("muted")] bool Muted);

/// <summary>surface.setViewport [M1]</summary>
public sealed record SurfaceSetViewportCommand(
    [property: JsonPropertyName("id")] string Id,
    [property: JsonPropertyName("w")] double W,
    [property: JsonPropertyName("h")] double H);

/// <summary>surface.setNowPlaying [M1]</summary>
public sealed record SurfaceSetNowPlayingCommand(
    [property: JsonPropertyName("id")] string Id,
    [property: JsonPropertyName("json")] string Json);

/// <summary>surface.setChrome [M1]</summary>
public sealed record SurfaceSetChromeCommand(
    [property: JsonPropertyName("id")] string Id,
    [property: JsonPropertyName("kind")] string Kind,
    [property: JsonPropertyName("face")] string Face,
    [property: JsonPropertyName("hidden")] bool Hidden);

/// <summary>surface.setFocused [stub until later milestone]</summary>
public sealed record SurfaceSetFocusedCommand(
    [property: JsonPropertyName("id")] string Id,
    [property: JsonPropertyName("focused")] bool Focused);

/// <summary>surface.setPageInput [stub until later milestone]</summary>
public sealed record SurfaceSetPageInputCommand(
    [property: JsonPropertyName("id")] string Id,
    [property: JsonPropertyName("active")] bool Active);

/// <summary>surface.sendKey [stub until later milestone]</summary>
public sealed record SurfaceSendKeyCommand(
    [property: JsonPropertyName("id")] string Id,
    [property: JsonPropertyName("key")] string Key);

/// <summary>surface.hover [M1]</summary>
public sealed record SurfaceHoverCommand(
    [property: JsonPropertyName("id")] string Id,
    [property: JsonPropertyName("x")] double X,
    [property: JsonPropertyName("y")] double Y);

/// <summary>surface.scrub [M1]</summary>
public sealed record SurfaceScrubCommand(
    [property: JsonPropertyName("id")] string Id,
    [property: JsonPropertyName("x")] double X,
    [property: JsonPropertyName("y")] double Y,
    [property: JsonPropertyName("press")] bool Press);

/// <summary>surface.typeText [stub until later milestone]</summary>
public sealed record SurfaceTypeTextCommand(
    [property: JsonPropertyName("id")] string Id,
    [property: JsonPropertyName("text")] string Text);

/// <summary>surface.evaluate (request lane — answer via PrismRuntime.resolve) [M1]</summary>
public sealed record SurfaceEvaluateCommand(
    [property: JsonPropertyName("id")] string Id,
    [property: JsonPropertyName("js")] string Js);

/// <summary>surface.veilImagery (request lane — answer via PrismRuntime.resolve) [M1]</summary>
public sealed record SurfaceVeilImageryCommand(
    [property: JsonPropertyName("source")] string Source);

/// <summary>surface.captureAudio [stub until later milestone]</summary>
public sealed record SurfaceCaptureAudioCommand(
    [property: JsonPropertyName("enable")] bool Enable);

/// <summary>surface.createVisualization [M1]</summary>
public sealed record SurfaceCreateVisualizationCommand(
    [property: JsonPropertyName("id")] string Id,
    [property: JsonPropertyName("style")] string Style,
    [property: JsonPropertyName("source")] string Source,
    [property: JsonPropertyName("artwork")] string Artwork,
    [property: JsonPropertyName("spill")] bool Spill);

/// <summary>surface.setVisualizationFeed [M1]</summary>
public sealed record SurfaceSetVisualizationFeedCommand(
    [property: JsonPropertyName("id")] string Id,
    [property: JsonPropertyName("json")] string Json);

/// <summary>surface.setPresence [M1]</summary>
public sealed record SurfaceSetPresenceCommand(
    [property: JsonPropertyName("id")] string Id,
    [property: JsonPropertyName("presence")] string Presence,
    [property: JsonPropertyName("rect")] ChannelRect Rect,
    [property: JsonPropertyName("durationMs")] double DurationMs);

/// <summary>ui.route [M1]</summary>
public sealed record UiRouteCommand(
    [property: JsonPropertyName("route")] string Route,
    [property: JsonPropertyName("source")] string Source,
    [property: JsonPropertyName("id")] string? Id = null);

/// <summary>ui.tapResult [M1]</summary>
public sealed record UiTapResultCommand(
    [property: JsonPropertyName("id")] string Id,
    [property: JsonPropertyName("action")] string Action,
    [property: JsonPropertyName("did")] string Did,
    [property: JsonPropertyName("audio")] string? Audio = null,
    [property: JsonPropertyName("error")] string? Error = null);

/// <summary>display.setBrightness [stub until later milestone]</summary>
public sealed record DisplaySetBrightnessCommand(
    [property: JsonPropertyName("value")] double Value);

/// <summary>display.setPower [stub until later milestone]</summary>
public sealed record DisplaySetPowerCommand(
    [property: JsonPropertyName("state")] string State);

/// <summary>media.launch [stub until later milestone]</summary>
public sealed record MediaLaunchCommand(
    [property: JsonPropertyName("package")] string Package,
    [property: JsonPropertyName("deepLink")] string? DeepLink = null);

/// <summary>media.setSpeakers [stub until later milestone]</summary>
public sealed record MediaSetSpeakersCommand(
    [property: JsonPropertyName("mode")] string Mode);

/// <summary>media.listApps (request lane — answer via PrismRuntime.resolve) [stub until later milestone]</summary>
public sealed record MediaListAppsCommand();

/// <summary>media.appSkip (request lane — answer via PrismRuntime.resolve) [stub until later milestone]</summary>
public sealed record MediaAppSkipCommand(
    [property: JsonPropertyName("package")] string Package,
    [property: JsonPropertyName("target")] string Target);

/// <summary>media.appType (request lane — answer via PrismRuntime.resolve) [stub until later milestone]</summary>
public sealed record MediaAppTypeCommand(
    [property: JsonPropertyName("package")] string Package,
    [property: JsonPropertyName("text")] string Text);

/// <summary>media.appBack (request lane — answer via PrismRuntime.resolve) [stub until later milestone]</summary>
public sealed record MediaAppBackCommand(
    [property: JsonPropertyName("package")] string Package);

/// <summary>media.serveAudio [stub until later milestone]</summary>
public sealed record MediaServeAudioCommand(
    [property: JsonPropertyName("transport")] string Transport,
    [property: JsonPropertyName("enable")] bool Enable);

/// <summary>media.webrtcOffer (request lane — answer via PrismRuntime.resolve) [stub until later milestone]</summary>
public sealed record MediaWebrtcOfferCommand(
    [property: JsonPropertyName("listener")] string Listener,
    [property: JsonPropertyName("offerSdp")] string OfferSdp);

/// <summary>media.webrtcIce [stub until later milestone]</summary>
public sealed record MediaWebrtcIceCommand(
    [property: JsonPropertyName("listener")] string Listener,
    [property: JsonPropertyName("candidate")] string Candidate);

/// <summary>media.webrtcClose [stub until later milestone]</summary>
public sealed record MediaWebrtcCloseCommand(
    [property: JsonPropertyName("listener")] string Listener);

/// <summary>input.startPairing [stub until later milestone]</summary>
public sealed record InputStartPairingCommand();

/// <summary>input.listRemotes (request lane — answer via PrismRuntime.resolve) [stub until later milestone]</summary>
public sealed record InputListRemotesCommand();

/// <summary>update.fetchManifest (request lane — answer via PrismRuntime.resolve) [stub until later milestone]</summary>
public sealed record UpdateFetchManifestCommand(
    [property: JsonPropertyName("url")] string Url);

/// <summary>update.apply (request lane — answer via PrismRuntime.resolve) [stub until later milestone]</summary>
public sealed record UpdateApplyCommand(
    [property: JsonPropertyName("release")] System.Text.Json.JsonElement? Release = null);

/// <summary>store.set [M1]</summary>
public sealed record StoreSetCommand(
    [property: JsonPropertyName("key")] string Key,
    [property: JsonPropertyName("value")] string Value);

/// <summary>alarm.setTone [stub until later milestone]</summary>
public sealed record AlarmSetToneCommand(
    [property: JsonPropertyName("playing")] bool Playing);

/// <summary>net.submitCompatReport [stub until later milestone]</summary>
public sealed record NetSubmitCompatReportCommand(
    [property: JsonPropertyName("report")] string Report);

/// <summary>net.applyBlockHosts [stub until later milestone]</summary>
public sealed record NetApplyBlockHostsCommand(
    [property: JsonPropertyName("sourceId")] string SourceId,
    [property: JsonPropertyName("name")] string Name,
    [property: JsonPropertyName("hosts")] System.Text.Json.JsonElement? Hosts = null);

/// <summary>net.fetchStatic (request lane — answer via PrismRuntime.resolve) [M1]</summary>
public sealed record NetFetchStaticCommand(
    [property: JsonPropertyName("url")] string Url);

/// <summary>net.fetchKeyed (request lane — answer via PrismRuntime.resolve) [M1]</summary>
public sealed record NetFetchKeyedCommand(
    [property: JsonPropertyName("url")] string Url,
    [property: JsonPropertyName("headers")] string Headers);

/// <summary>runtime.error [M1]</summary>
public sealed record RuntimeErrorCommand(
    [property: JsonPropertyName("message")] string Message);

/// <summary>remote.paired [M1]</summary>
public sealed record RemotePairedCommand(
    [property: JsonPropertyName("token")] string Token);

/// <summary>remote.pairing [M1]</summary>
public sealed record RemotePairingCommand(
    [property: JsonPropertyName("url")] string Url,
    [property: JsonPropertyName("token")] string Token);

/// <summary>remote.paired-count [M1]</summary>
public sealed record RemotePairedCountCommand(
    [property: JsonPropertyName("n")] double N);

/// <summary>http.response [M1]</summary>
public sealed record HttpResponseCommand(
    [property: JsonPropertyName("requestId")] double RequestId,
    [property: JsonPropertyName("status")] double Status,
    [property: JsonPropertyName("body")] string Body,
    [property: JsonPropertyName("contentType")] string ContentType);

public static class ChannelSchema
{
    /// <summary>op → is request-lane (needs a resolve answer).</summary>
    public static readonly System.Collections.Generic.Dictionary<string, bool> RequestLane = new()
    {
        ["surface.create"] = false,
        ["surface.destroy"] = false,
        ["surface.setRect"] = false,
        ["surface.setOpacity"] = false,
        ["surface.setZ"] = false,
        ["surface.setVisible"] = false,
        ["surface.goBack"] = true,
        ["surface.navigate"] = false,
        ["surface.inject"] = false,
        ["surface.freeze"] = false,
        ["surface.reveal"] = false,
        ["surface.suspend"] = false,
        ["surface.resume"] = false,
        ["surface.setPeek"] = false,
        ["surface.showIntermission"] = false,
        ["surface.hideIntermission"] = false,
        ["surface.setIntermissionSkip"] = false,
        ["surface.setAdInfo"] = false,
        ["surface.setMuted"] = false,
        ["surface.setViewport"] = false,
        ["surface.setNowPlaying"] = false,
        ["surface.setChrome"] = false,
        ["surface.setFocused"] = false,
        ["surface.setPageInput"] = false,
        ["surface.sendKey"] = false,
        ["surface.hover"] = false,
        ["surface.scrub"] = false,
        ["surface.typeText"] = false,
        ["surface.evaluate"] = true,
        ["surface.veilImagery"] = true,
        ["surface.captureAudio"] = false,
        ["surface.createVisualization"] = false,
        ["surface.setVisualizationFeed"] = false,
        ["surface.setPresence"] = false,
        ["ui.route"] = false,
        ["ui.tapResult"] = false,
        ["display.setBrightness"] = false,
        ["display.setPower"] = false,
        ["media.launch"] = false,
        ["media.setSpeakers"] = false,
        ["media.listApps"] = true,
        ["media.appSkip"] = true,
        ["media.appType"] = true,
        ["media.appBack"] = true,
        ["media.serveAudio"] = false,
        ["media.webrtcOffer"] = true,
        ["media.webrtcIce"] = false,
        ["media.webrtcClose"] = false,
        ["input.startPairing"] = false,
        ["input.listRemotes"] = true,
        ["update.fetchManifest"] = true,
        ["update.apply"] = true,
        ["store.set"] = false,
        ["alarm.setTone"] = false,
        ["net.submitCompatReport"] = false,
        ["net.applyBlockHosts"] = false,
        ["net.fetchStatic"] = true,
        ["net.fetchKeyed"] = true,
        ["runtime.error"] = false,
        ["remote.paired"] = false,
        ["remote.pairing"] = false,
        ["remote.paired-count"] = false,
        ["http.response"] = false,
    };
    /// <summary>ops the M1 host implements; every other op logs + (request lane) resolves with an 'unsupported' error.</summary>
    public static readonly System.Collections.Generic.HashSet<string> M1 = new()
    {
        "surface.create",
        "surface.destroy",
        "surface.setRect",
        "surface.setOpacity",
        "surface.setZ",
        "surface.navigate",
        "surface.inject",
        "surface.freeze",
        "surface.reveal",
        "surface.suspend",
        "surface.resume",
        "surface.setPeek",
        "surface.showIntermission",
        "surface.hideIntermission",
        "surface.setIntermissionSkip",
        "surface.setAdInfo",
        "surface.setMuted",
        "surface.setViewport",
        "surface.setNowPlaying",
        "surface.setChrome",
        "surface.hover",
        "surface.scrub",
        "surface.evaluate",
        "surface.veilImagery",
        "surface.createVisualization",
        "surface.setVisualizationFeed",
        "surface.setPresence",
        "ui.route",
        "ui.tapResult",
        "store.set",
        "net.fetchStatic",
        "net.fetchKeyed",
        "runtime.error",
        "remote.paired",
        "remote.pairing",
        "remote.paired-count",
        "http.response",
    };
}
